# Generated by Django 3.2.5 on 2022-11-18 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('make', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('serialNum', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('durationTime', models.IntegerField(null=True)),
                ('lastServiceDate', models.DateField()),
                ('durationDistance', models.IntegerField(null=True)),
                ('lastServiceDistance', models.IntegerField(null=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=255)),
                ('model', models.CharField(default='', max_length=255)),
                ('serialNum', models.IntegerField(null=True)),
                ('boughtDate', models.DateField()),
                ('consumedDate', models.DateField()),
                ('removedDate', models.DateField()),
                ('maintenanceSchedule', models.IntegerField(null=True)),
                ('maintenanceUnits', models.CharField(default='', max_length=255)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.object')),
            ],
        ),
    ]
