# Generated by Django 3.2.5 on 2022-11-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20221118_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='make',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='model',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='nickname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='object',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
